### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Motchanyy** [mytja/harmonoid-music-bot#5]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from commands import *
  File "/var/www/123/music/commands/__init__.py", line 6, in <module>
    from scripts.youtube import YouTube
  File "/var/www/123/music/scripts/youtube.py", line 1, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

**Comment by alexmercerind** [comment]
```
pip3 install httpx
```

**Comment by mytja** [comment]
You have to install all dependencies using following command:
```
python -m pip install -r requirements.txt
```
You also have to install ffmpeg. This can be done on Ubuntu/Debian with following command:
```
sudo apt install ffmpeg
```
Simplest is to use a prebuild docker container, for which I will write instructions quite soon in README.
Let me know if you have any errors, otherwise I'm closing this for now.
